import type { AxiosInstance } from 'axios'
import type { GeneralSuccessResponse } from '../api'

/**
 * Parameters for SendE2eeTestNotification API
 * @since Zulip 11.0 (feature level 420)
 * @see https://zulip.com/api/e2ee-test-notify#parameters
 */
export type SendE2eeTestNotificationParams = {
  /**
   * Device ID
   * @since Zulip 12.0 (feature level 468)
   * @see https://zulip.com/api/e2ee-test-notify#parameter-device_id
   */
  device_id?: number
}

/**
 * The type of device token
 */
export type E2eeDeviceTokenKind = 'fcm' | 'apns'

/**
 * Parameters for RegisterE2eeDevice API
 * @since Zulip 11.0 (feature level 406)
 * @see https://zulip.com/api/register-push-device#parameters
 */
export type RegisterE2eeDeviceParams = {
  /**
   * Device ID from RegisterDevice API
   * @see https://zulip.com/api/register-push-device#parameter-device_id
   */
  device_id: number
  /**
   * A random unsigned 32-bit integer generated by the client as an identifier for push_key
   * @see https://zulip.com/api/register-push-device#parameter-push_key_id
   */
  push_key_id?: number
  /**
   * Key that the client would like the server to use to encrypt notifications,
   * encoded with Base64
   * @since Zulip 12.0 (feature level 432)
   * @see https://zulip.com/api/register-push-device#parameter-push_key
   */
  push_key?: string
  /**
   * Whether the token was generated by FCM or APNs
   * @see https://zulip.com/api/register-push-device#parameter-token_kind
   */
  token_kind?: E2eeDeviceTokenKind
  /**
   * Identifier for the FCM/APNs provided token to the device, produced by
   * taking the first 8 bytes of the SHA-256 hash of the token,
   * then encoding those bytes using standard Base64 encoding
   * @see https://zulip.com/api/register-push-device#parameter-token_id
   */
  token_id?: string
  /**
   * Which of the bouncer's public keys the client used to encrypt the
   * PushRegistration dictionary.
   * The public key is encoded using standard Base64 encoding
   * @see https://zulip.com/api/register-push-device#parameter-bouncer_public_key
   */
  bouncer_public_key?: string
  /**
   * Ciphertext generated by encrypting a PushRegistration dictionary using
   * the bouncer_public_key, encoded using Base64
   * @see https://zulip.com/api/register-push-device#parameter-encrypted_push_registration
   */
  encrypted_push_registration?: string
}

/**
 * Parameters for RegisterRemotePushDevice API
 * @since Zulip 11.0 (feature level 406)
 * @see https://zulip.com/api/register-remote-push-device#parameters
 */
export type RegisterRemotePushDeviceParams = {
  /**
   * The UUID of the realm to which the push device being registered belongs
   * @see https://zulip.com/api/register-remote-push-device#parameter-realm_uuid
   */
  realm_uuid: string
  /**
   * The token_id value provided by the mobile client to RegisterE2eeDevice API
   * @since Zulip 12.0 (feature level 468)
   * @see  https://zulip.com/api/register-remote-push-device#parameter-token_id
   */
  token_id: string
  /**
   * The encrypted_push_registration value provided by the mobile client to RegisterE2eeDevice API
   * @see https://zulip.com/api/register-remote-push-device#parameter-encrypted_push_registration
   */
  encrypted_push_registration: string
  /**
   * The bouncer_public_key value provided by the mobile client to RegisterE2eeDevice API
   * @see https://zulip.com/api/register-remote-push-device#parameter-bouncer_public_key
   */
  bouncer_public_key: string
}

/**
 * Send E2EE test notification to the target device or all devices
 * @param client Axios client initialized by generateCallApi function in api.ts
 * @param params API parameters
 * @returns The response of SendE2eeTestNotification API
 * @since Zulip 11.0 (feature level 420)
 * @see https://zulip.com/api/e2ee-test-notify
 */
export async function sendE2eeTestNotification(
  client: AxiosInstance,
  params: SendE2eeTestNotificationParams = {},
) {
  const body = new URLSearchParams()
  if (params.device_id !== undefined) {
    body.append('device_id', String(params.device_id))
  }

  const resp = await client.post<GeneralSuccessResponse>(
    '/mobile_push/e2ee/test_notification',
    body,
  )

  return resp.data
}

/**
 * Register a device to E2EE mobile push notifications, or update such a registration
 * @param client Axios client initialized by generateCallApi function in api.ts
 * @param params API parameters
 * @returns The response of RegisgterE2eeDevice API
 * @since Zulip 11.0 (feature level 406)
 * @see https://zulip.com/api/register-push-device
 */
export async function registerE2eeDevice(
  client: AxiosInstance,
  params: RegisterE2eeDeviceParams,
) {
  const body = new URLSearchParams()

  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null) {
      continue
    }
    body.append(key, String(value))
  }

  const resp = await client.post<GeneralSuccessResponse>(
    '/mobile_push/register',
    body,
  )

  return resp.data
}

/**
 * Register a push device to bouncer to receive E2EE push notification
 * @param client Axios client initialized by generateCallApi function in api.ts
 * @param params API parameters
 * @returns The response of RegisterRemotePushDevice API
 * @since Zulip 11.0 (feature level 406)
 * @see https://zulip.com/api/register-remote-push-device
 */
export async function registerRemotePushDevice(
  client: AxiosInstance,
  params: RegisterRemotePushDeviceParams,
) {
  const body = new URLSearchParams(params)

  const resp = await client.post<GeneralSuccessResponse>(
    '/remotes/push/e2ee/register',
    body,
  )

  return resp.data
}
